name: Build and Publish

on:
  release:
    types: [published]

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install build packages
        run: |
          pip install enum34 requests six python-dateutil sphinx sphinx_rtd_theme setuptools-scm gitchangelog mako collective.checkdocs wheel twine 
      - name: Build distribution
        run: |
          python setup.py checkdocs
          python setup.py sdist bdist_wheel
      - name: Archive distribution artifacts
        uses: actions/upload-artifact@v3
        with:
          name: distribution
          path: dist
          retention-days: 5
      - name: Test Publish distribution
        run: twine upload -u __token__ -p ${{ secrets.TEST_PYPI_TOKEN}} -r testpypi dist/*