name: Test Build

on: [push]

jobs:
  mock-api-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install certifi enum34 requests six python-dateutil coverage coveralls[yaml] pytest pytest-instafail requests-toolbelt
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Clone smartsheet/smartsheet-sdk-tests PRIVATE repository
        uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'smartsheet'
          repository: 'smartsheet-sdk-tests'
          access-token: ${{ secrets.SDK_TEST_ACCESS_TOKEN }}
      - name: Setup Mock API
        run: |
          smartsheet-sdk-tests/travis_scripts/install_wiremock.sh
          smartsheet-sdk-tests/travis_scripts/start_wiremock.sh
      - name: Run mock API tests
        run: |
          coverage run --source=smartsheet setup.py test -a tests/mock_api/
          coverage lcov
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: "coverage.lcov"
  
  integration-tests:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      max-parallel: 2
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    env:
      SMARTSHEET_ACCESS_TOKEN: ${{ secrets.INTEGRATION_TEST_SMARTSHEET_ACCESS_TOKEN }}
      SMARTSHEET_FIXTURE_USERS: ${{ secrets.SMARTSHEET_FIXTURE_USERS}}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install certifi enum34 requests six python-dateutil coverage coveralls[yaml] pytest pytest-instafail requests-toolbelt
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run integration tests
        run: |
          coverage run --source=smartsheet setup.py test -a tests/integration/
          coverage lcov
  
  build-packages-test:
    runs-on: ubuntu-latest
    needs: [mock-api-test, integration-tests]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install build packages
        run: |
          pip install enum34 requests six python-dateutil setuptools-scm gitchangelog mako collective.checkdocs wheel twine 
      - name: Build distribution
        run: |
          python setup.py checkdocs
          python setup.py sdist bdist_wheel
      - name: Archive distribution artifacts
        uses: actions/upload-artifact@v3
        with:
          name: distribution
          path: dist
          retention-days: 5

  build-documentation-test:
    runs-on: ubuntu-latest
    needs: [build-packages-test]
    steps:
      - uses: actions/checkout@v3
      - name: Install documentation tools
        run: |
          pip install sphinx sphinx_rtd_theme setuptools-scm
      - name: Generate API documentation 
        run: sphinx-apidoc -o docs-source smartsheet 
      - name: Generate HTML
        run: sphinx-build -b html -d docs-source/_build/doctrees docs-source/. docs-source/_build/html
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: html-docs
          path: docs/build/html/
          retention-days: 5
